#Heros
iron_man = Hero.create(name: "Iron Man", strength: "Intelligence", weakness: "Magic", power_level: 8)
war_machine = Hero.create(name: "War Machine", strength: "Combat", weakness: "Magic", power_level: 7)
captain_america = Hero.create(name: "Captain America", strength: "Hand Combat", weakness: "Infinity Stones", power_level: 8)
winter_soldier = Hero.create(name: "White Wolf", strength: "Hand Combat", weakness: "Infinity Stones", power_level: 7)
thor = Hero.create(name: "Thor", strength: "Thunder", weakness: "Infinity Stones", power_level: 10)
loki = Hero.create(name: "Loki", strength: "Magic", weakness: "Infinity Stones", power_level: 9)
black_widow = Hero.create(name: "Black Widow", strength: "Hand Combat", weakness: "Super Strength", power_level: 5)
hawkeye = Hero.create(name: "Hawkeye", strength: "Site", weakness: "Super Strength", power_level: 5)
falcon = Hero.create(name: "Falcon", strength: "Combat", weakness: "Super Strength", power_level: 5)
hulk = Hero.create(name: "Hulk", strength: "Combat", weakness: "Magic", power_level: 9)
black_panther = Hero.create(name: "Black Panther", strength: "Combat", weakness: "Infinity Stones", power_level: 7)
doctor_strange = Hero.create(name: "Doctor Strange", strength: "Magic", weakness: "Hand Combat", power_level: 9)
spider_man = Hero.create(name: "Spider Man", strength: "Combat", weakness: "Infinity Stones", power_level: 7)
groot = Hero.create(name: "Groot", strength: "Combat", weakness: "Magic", power_level: 6)

#Powers
arc = Power.create(name: "Arc Reactor", description: "Powers the Iron Man Suits", power_tier:"3")
human_experiment = Power.create(name: "Human Experiment", description: "Some experiment gone wrong or right", power_tier:"3")
god = Power.create(name: "God powers", description: "Super strength, long life, use of powers", power_tier:"5")
hammer = Power.create(name: "Mjonir", description: "Weapon forged in a dying star", power_tier:"5")
combat = Power.create(name: "Combat", description: "Particular set of skills", power_tier:"1")
vibranium = Power.create(name:"Vibranium", description: "The rarest and strongest metal on earth", power_tier:"3")
mystic_arts = Power.create(name: "Mystic Arts", description: "Sorcery, the ability to not make scientific sense", power_tier:"4")
flight = Power.create(name: "Flight", description: "I believe I can flyy", power_tier:"2")

#SuperPowers
SuperPower.create(hero_id: 1, power_id: 1)
SuperPower.create(hero_id: 1, power_id: 5)
SuperPower.create(hero_id: 2, power_id: 1)
SuperPower.create(hero_id: 2, power_id: 5)
SuperPower.create(hero_id: 3, power_id: 2)
SuperPower.create(hero_id: 3, power_id: 5)
SuperPower.create(hero_id: 3, power_id: 6)
SuperPower.create(hero_id: 4, power_id: 5)
SuperPower.create(hero_id: 4, power_id: 6)
SuperPower.create(hero_id: 5, power_id: 3)
SuperPower.create(hero_id: 5, power_id: 4)
SuperPower.create(hero_id: 6, power_id: 3)
SuperPower.create(hero_id: 6, power_id: 7)
SuperPower.create(hero_id: 7, power_id: 5)
SuperPower.create(hero_id: 8, power_id: 5)
SuperPower.create(hero_id: 9, power_id: 5)
SuperPower.create(hero_id: 9, power_id: 1)
SuperPower.create(hero_id: 10, power_id: 2)
SuperPower.create(hero_id: 10, power_id: 5)
SuperPower.create(hero_id: 11, power_id: 6)
SuperPower.create(hero_id: 11, power_id: 5)
SuperPower.create(hero_id: 11, power_id: 7)
SuperPower.create(hero_id: 12, power_id: 2)
SuperPower.create(hero_id: 12, power_id: 5)
SuperPower.create(hero_id: 13, power_id: 5)
SuperPower.create(hero_id: 13, power_id: 1)
SuperPower.create(hero_id: 13, power_id: 2)
SuperPower.create(hero_id: 14, power_id: 5)
